### ISSUE TITLE
There is a problem with js/jsx

### ISSUE THREAD

**Issue by BruceCham** [loggur/webpack-module-hot-accept#2]
你好：  

After the `js/jsx` file changes, the browser does not render again or Refresh the browser (`Css` is normal), it will only take effect after triggering `render()`

**Comment by Francisc** [comment]
Any update on this?

**Comment by timbur** [comment]
What is your setup like?  This plugin is really outdated so I don't know if it will even work with the latest webpack, react, etc.  I haven't used this plugin in a very long time myself.

With that said, `render()` isn't triggered because of the way react works.  You'll have to re-render when the hot update occurs.

I think I heard something about react possibly including hot reloading out of the box in the near future.

**Comment by Francisc** [comment]
Hello.

I'm using `gulp` with `browser-sync` and `webpack-dev-middleware` and `webpack-hot-middleware`.
All at latest version.

I was hoping `webpack-module-hot-accept` would spare me from having to write all that `if(module.hot)` code in each file.

It seems like it's working, CSS reloads, JS reloads. Just changes inside of the `render()` method do not.

**Comment by timbur** [comment]
This plugin is decoupled from react.  There is no way for it to know that the `render` function should be called again.

In whatever file you're using for mounting your react app, you'll need to re-render on hot updates - e.g.:

```js
import React from 'react';
import { render } from 'react-dom';
import App, { components } from './components/App';
import defaultProps from './defaultProps';

function renderApp(props, element = document.getElementById('root')) {
  return render(<App { ...props } />, element);
}

renderApp(defaultProps);

export default renderApp;

if (process.env.NODE_ENV !== 'production') {
  if (module.hot) {
    module.hot.accept('./components/App', () => {
      renderApp(defaultProps);
    });
  }
}
```

Obviously change that to fit your use case.

**Comment by Francisc** [comment]
You're right, thank you for your help.
